platform: linux
image_resource:
  type: docker-image
inputs:
  - name: gpdb_src
  - name: bin_gpdb
outputs:
params:
  TEST_OS: ""
  TARGET_OS:
run:
  path: gpdb_src/concourse/scripts/gpload_stress.bash
